### ISSUE TITLE
Thunderbird 60.0

### ISSUE THREAD

**Issue by klausatlas** [alainfrisch/nostalgy#52] opened 2018-09-09 13:03 UTC
Hi,

nostalgy is a great extension but it stopped working with thunderbird 60. Will it be updated?

**Comment by caugner** [comment] 2018-09-10 07:27
It looks like @alainfrisch is actively working on this, see [this commit](https://github.com/alainfrisch/nostalgy/commit/e6b1084f966ecb4e9e6ec62a7192ced760e9c87c). 🎉

**Comment by alainfrisch** [comment] 2018-09-10 07:28
Duplicate of #46.

**Closed by alainfrisch** 2018-09-10 07:28 UTC
